### ISSUE TITLE
rDNS for ipv4 is invalid, please fix

### ISSUE THREAD

**Issue by RaidAndFade** [RaidAndFade/ipv6-tools#2]
https://github.com/RaidAndFade/ipv6-tools/blob/fd88e729033c0ed054b46eb075892a95742baa6e/mainpage.js#L502

On this line, it should be in-addr instead of ip-addr.

**Comment by tamarantula** [comment]
Can I do this?

**Comment by RaidAndFade** [comment]
@tamarantula Sure! I've assigned the issue to you.
